name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') && success() && github.repository == 'klxiaoniu/QQVersionList' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup local.properties
        run: echo "" > local.properties

      # 向 app 目录插入 google-services.json，文件内容来自 Secret
      - name: Insert google-services.json
        run: |
          cat <<EOF > app/google-services.json
          ${{ secrets.GOOGLE_SERVICES }}
          EOF
        shell: bash

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGN_KEYSTORE_BASE64 }} | base64 -d > keystore.jks
          ./gradlew build
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}

      - name: Upload release
        uses: actions/upload-artifact@v4.5.0
        with:
          path: ${{github.workspace}}/app/build/outputs/apk/release/*.apk
          name: QQVersionList-release-${{ github.event.head_commit.id }}
          retention-days: 90

      - name: Upload mappings
        uses: actions/upload-artifact@v4.5.0
        with:
          path: ${{github.workspace}}/app/build/outputs/mapping/release/mapping.txt
          name: QQVersionList-release-${{ github.event.head_commit.id }}-mapping
          retention-days: 90